import { existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { build } from 'esbuild';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

// esbuild bundles from TypeScript source, but our imports use the `.js`
// extension required by Node ESM. Map relative `.js` specifiers back to the
// sibling `.ts` file so the action bundles directly from src/.
const tsResolvePlugin = {
  name: 'ts-resolve',
  setup(b) {
    b.onResolve({ filter: /\.js$/ }, (args) => {
      if (args.kind === 'entry-point' || !args.path.startsWith('.')) return;
      const tsPath = resolve(args.resolveDir, args.path.replace(/\.js$/, '.ts'));
      if (existsSync(tsPath)) return { path: tsPath };
      return undefined;
    });
  },
};

await build({
  entryPoints: [resolve(root, 'action/main.ts')],
  bundle: true,
  platform: 'node',
  target: 'node24',
  format: 'cjs',
  outfile: resolve(root, 'action/index.cjs'),
  plugins: [tsResolvePlugin],
  banner: {
    js: '// Bundled GitHub Action — generated by `npm run action:build`. Do not edit by hand.',
  },
});

console.log('Built action/index.cjs');
